version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
### Workspace Utilities ##################################
    workspace:
      build:
        context: ./docker/workspace
      volumes:
        - ./:/var/www
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./docker/php-fpm
      volumes:
        - ./docker/php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
        - ./:/var/www
      expose:
        - "9000"
      depends_on:
        - workspace
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      build:
        context: ./docker/nginx
      volumes:
        - ./:/var/www
        - ./storage/logs/nginx/:/var/log/nginx
        - ./docker/nginx/sites:/etc/nginx/sites-available
        - ./docker/nginx/ssl:/etc/nginx/ssl
      ports:
        - "80:1080"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
